apiVersion: v1
kind: Pod
metadata:
  name: ch10converter
  labels:
    app: ch10converter
spec:
  containers:
  - name: ch10converter
    image: 431396205827.dkr.ecr.us-west-2.amazonaws.com/ch10converter:v0.9
    env:
    - name: HS_ENDPOINT
      value: http://100.66.25.138
    - name: HS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: hsds-firefly-admin-pswd
          key: hs_password
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-auth-keys
          key: aws_access_key_id
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
            name: aws-auth-keys
            key: aws_secret_access_key
    - name: AWS_REGION
      value: us-west-2
    - name: AWS_S3_GATEWAY
      value: http://s3.us-west-2.amazonaws.com
